### ISSUE TITLE
Fix interface name validation checks

### ISSUE THREAD

**Issue by jaysheth2** [l3af-project/eBPF-Package-Repository#25]
Currently, tc-root can be attached to the interface whose name contains only alphabets or digits. However, in case of the hypervisors, tap interface generally contains a hyphen. Hence, we need to fix traffic mirroring code and allow interface names with hyphens as well.

**Comment by evershalik** [comment]
Hey @jaysheth2, If you don't mind, I would like to take on this issue to help resolve it. Would that be okay with you?

**Comment by jaysheth2** [comment]
Sure @evershalik, please go ahead. 
Thank you for your help
